### ISSUE TITLE
Maybe there is a small error

### ISSUE THREAD

**Issue by dongdong7876** [tudelft-cda-lab/SECLEDS#2]
Hi, maybe there is a small error on line 12 of eval_pairwise.pyx, `def adjacency_accuracy(labels, predictions, pairs, bs=-1):` or `def adjacency_accuracy(predictions, labels, pairs, bs=-1):`? I think `predictions` may be in the first position.

**Comment by azqanadeem** [comment]
Good catch! It doesn't really change the results but it's good to fix for semantics.
